 
services:
  api:
    build:
      context: .
      dockerfile: E-Commerce-Inern-Project.API/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - rabbitmq
    environment:
      RabbitMQ_HostName: rabbitmq
      RabbitMQ_UserName: user
      RabbitMQ_Password: password
      RabbitMQ_Port: 5672
    networks:
      - ecommerce-network

  rabbitmq:
    image: rabbitmq:3.13-management
    ports: 
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - ecommerce-network
    
  redis:
    image: redis:latest
    ports: 
     - "6379:6379"
    volumes:
     - D:\NEw_laptop_Boda\FullStack_Projects\E-Commerce-Intern-Project\Redis-Cache:/data
    networks:
        - ecommerce-network

networks:
  ecommerce-network: