// <auto-generated />
using System;
using E_Commerce_Inern_Project.Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Commerce_Inern_Project.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402094550_newDbinit")]
    partial class newDbinit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Address", b =>
                {
                    b.Property<Guid>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLabel")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("AreaID")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BackUpAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BackUpPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<Guid>("CityID")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MainAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserID")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AddressID");

                    b.HasIndex("AreaID");

                    b.HasIndex("CityID");

                    b.HasIndex("UserID");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Area", b =>
                {
                    b.Property<Guid>("AreaID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CityID")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("AreaID");

                    b.HasIndex("CityID");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.BannerSlide", b =>
                {
                    b.Property<Guid>("BannerSlideID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccentColorID")
                        .HasMaxLength(20)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BackgroundColorID")
                        .HasMaxLength(200)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CTA")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BannerSlideID");

                    b.HasIndex("AccentColorID");

                    b.HasIndex("BackgroundColorID");

                    b.ToTable("BannerSlides");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Cart", b =>
                {
                    b.Property<Guid>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CartID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.CartItems", b =>
                {
                    b.Property<Guid>("CartItemID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CartID")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductID")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemID");

                    b.HasIndex("CartID");

                    b.HasIndex("ProductID");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Category", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HashImage")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentCategoryID")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryID");

                    b.HasIndex("ParentCategoryID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.City", b =>
                {
                    b.Property<Guid>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("CityID");

                    b.ToTable("City");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Colors", b =>
                {
                    b.Property<Guid>("ColorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorHexCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ColorID");

                    b.HasIndex("ColorName")
                        .IsUnique();

                    b.ToTable("Color");

                    b.HasData(
                        new
                        {
                            ColorID = new Guid("179d4d45-54a7-48da-82f4-ad4673854bd2"),
                            ColorHexCode = "#000000",
                            ColorName = "Black",
                            IsDeleted = false
                        },
                        new
                        {
                            ColorID = new Guid("97ca3fd7-7860-4961-8dde-d90cec05e3cf"),
                            ColorHexCode = "#FFFFFF",
                            ColorName = "White",
                            IsDeleted = false
                        },
                        new
                        {
                            ColorID = new Guid("91099764-4ff3-4a91-8f84-3bf913ca3b6c"),
                            ColorHexCode = "#FF0000",
                            ColorName = "Red",
                            IsDeleted = false
                        },
                        new
                        {
                            ColorID = new Guid("438b0e6e-af1f-4bf1-9e18-ef5a2ddd94f3"),
                            ColorHexCode = "#0000FF",
                            ColorName = "Blue",
                            IsDeleted = false
                        },
                        new
                        {
                            ColorID = new Guid("220096a6-c67a-4640-83f2-ae526a2a542d"),
                            ColorHexCode = "#008000",
                            ColorName = "Green",
                            IsDeleted = false
                        },
                        new
                        {
                            ColorID = new Guid("0fb24adb-a140-4c50-9eb6-4d948408f30d"),
                            ColorHexCode = "#FFFF00",
                            ColorName = "Yellow",
                            IsDeleted = false
                        },
                        new
                        {
                            ColorID = new Guid("a3a07d13-c759-4920-a68a-47ef88e7594d"),
                            ColorHexCode = "#FFA500",
                            ColorName = "Orange",
                            IsDeleted = false
                        },
                        new
                        {
                            ColorID = new Guid("0a65996c-b895-42bc-af60-fac2f914376c"),
                            ColorHexCode = "#800080",
                            ColorName = "Purple",
                            IsDeleted = false
                        },
                        new
                        {
                            ColorID = new Guid("72a9cbb7-360c-4c75-97f7-680baf249a22"),
                            ColorHexCode = "#FFC0CB",
                            ColorName = "Pink",
                            IsDeleted = false
                        },
                        new
                        {
                            ColorID = new Guid("1b0856ec-68c8-49d5-9872-2a3f12c373ac"),
                            ColorHexCode = "#808080",
                            ColorName = "Gray",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Order", b =>
                {
                    b.Property<Guid>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("OrderCouponID")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PaymentID")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShippingCostID")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Subtotal")
                        .HasMaxLength(50)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserID")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderID");

                    b.HasIndex("AddressID");

                    b.HasIndex("OrderCouponID");

                    b.HasIndex("PaymentID");

                    b.HasIndex("ShippingCostID");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.OrderCoupons", b =>
                {
                    b.Property<Guid>("OrderCouponID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Discount")
                        .HasMaxLength(10)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("OrderCouponID");

                    b.ToTable("OrderCoupon");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.OrderItems", b =>
                {
                    b.Property<Guid>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderID")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductID")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Payments", b =>
                {
                    b.Property<Guid>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasMaxLength(100)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserID")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PaymentID");

                    b.HasIndex("UserID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Product", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<Guid>("CategoryID")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColorID")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashImage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasMaxLength(10)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Rating")
                        .HasMaxLength(10)
                        .HasColumnType("float");

                    b.Property<decimal?>("SalePrice")
                        .HasMaxLength(10)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SizeID")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Stock")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int>("TotalRating")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ColorID");

                    b.HasIndex("SizeID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.ProductRates", b =>
                {
                    b.Property<Guid>("RateID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductID")
                        .HasMaxLength(200)
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Rating")
                        .HasMaxLength(10)
                        .HasColumnType("float");

                    b.Property<Guid>("UserID")
                        .HasMaxLength(200)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RateID");

                    b.HasIndex("ProductID");

                    b.HasIndex("UserID");

                    b.ToTable("ProductRates");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.ShippingCosts", b =>
                {
                    b.Property<Guid>("ShippingCostID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AraeID")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("ShippingCost")
                        .HasMaxLength(10)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ShippingCostID");

                    b.HasIndex("AraeID")
                        .IsUnique();

                    b.ToTable("ShippingCosts");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Size", b =>
                {
                    b.Property<Guid>("SizeID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SizeName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("SizeID");

                    b.ToTable("Size");

                    b.HasData(
                        new
                        {
                            SizeID = new Guid("4f0406b9-fe94-487f-9049-0b28da2c9274"),
                            IsDeleted = false,
                            SizeName = "Small"
                        },
                        new
                        {
                            SizeID = new Guid("730323ea-7e2e-4ec1-98f2-78fa1aa7c5e9"),
                            IsDeleted = false,
                            SizeName = "Medium"
                        },
                        new
                        {
                            SizeID = new Guid("67af942f-aeeb-4a4d-964b-0effc559368e"),
                            IsDeleted = false,
                            SizeName = "Large"
                        },
                        new
                        {
                            SizeID = new Guid("d43285b3-b034-42cc-8795-e5fffb245654"),
                            IsDeleted = false,
                            SizeName = "X Large"
                        },
                        new
                        {
                            SizeID = new Guid("66a0c1c9-9db3-421a-87d0-f8c965687703"),
                            IsDeleted = false,
                            SizeName = "XX Large"
                        });
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.WishList", b =>
                {
                    b.Property<Guid>("WishlistID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WishlistID");

                    b.HasIndex("ProductID");

                    b.HasIndex("UserID");

                    b.ToTable("WishList");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bffbe3e7-4adf-4bb5-83db-6880f743d5da"),
                            ConcurrencyStamp = "1c23edf8-0bc4-41e4-bf72-f89f0594ead7",
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            RoleDescription = "Admin role with full permissions"
                        },
                        new
                        {
                            Id = new Guid("bcf2e140-cf5c-4352-a238-e04c7f220e64"),
                            ConcurrencyStamp = "3d02c4f7-16a9-47f9-be71-3e27a0b9c46b",
                            Name = "User",
                            NormalizedName = "USER",
                            RoleDescription = "User role with limited permissions"
                        });
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpirtation")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Address", b =>
                {
                    b.HasOne("E_Commerce_Inern_Project.Core.Domain.Entity.Area", "Area")
                        .WithMany("Addresses")
                        .HasForeignKey("AreaID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("E_Commerce_Inern_Project.Core.Domain.Entity.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("E_Commerce_Inern_Project.Core.Identity.ApplicationUser", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Area", b =>
                {
                    b.HasOne("E_Commerce_Inern_Project.Core.Domain.Entity.City", "City")
                        .WithMany("Areas")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.BannerSlide", b =>
                {
                    b.HasOne("E_Commerce_Inern_Project.Core.Domain.Entity.Colors", "AccentColor")
                        .WithMany()
                        .HasForeignKey("AccentColorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_Inern_Project.Core.Domain.Entity.Colors", "BackgroundColor")
                        .WithMany("BannerSlides")
                        .HasForeignKey("BackgroundColorID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AccentColor");

                    b.Navigation("BackgroundColor");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Cart", b =>
                {
                    b.HasOne("E_Commerce_Inern_Project.Core.Identity.ApplicationUser", "User")
                        .WithOne("Cart")
                        .HasForeignKey("E_Commerce_Inern_Project.Core.Domain.Entity.Cart", "UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.CartItems", b =>
                {
                    b.HasOne("E_Commerce_Inern_Project.Core.Domain.Entity.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("E_Commerce_Inern_Project.Core.Domain.Entity.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Category", b =>
                {
                    b.HasOne("E_Commerce_Inern_Project.Core.Domain.Entity.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Order", b =>
                {
                    b.HasOne("E_Commerce_Inern_Project.Core.Domain.Entity.Address", "Address")
                        .WithMany("orders")
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("E_Commerce_Inern_Project.Core.Domain.Entity.OrderCoupons", "OrderCoupon")
                        .WithMany("orders")
                        .HasForeignKey("OrderCouponID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("E_Commerce_Inern_Project.Core.Domain.Entity.Payments", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_Inern_Project.Core.Domain.Entity.ShippingCosts", "ShippingCosts")
                        .WithMany("orders")
                        .HasForeignKey("ShippingCostID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("E_Commerce_Inern_Project.Core.Identity.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("OrderCoupon");

                    b.Navigation("Payment");

                    b.Navigation("ShippingCosts");

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.OrderItems", b =>
                {
                    b.HasOne("E_Commerce_Inern_Project.Core.Domain.Entity.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("E_Commerce_Inern_Project.Core.Domain.Entity.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Payments", b =>
                {
                    b.HasOne("E_Commerce_Inern_Project.Core.Identity.ApplicationUser", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Product", b =>
                {
                    b.HasOne("E_Commerce_Inern_Project.Core.Domain.Entity.Category", "Category")
                        .WithMany("Product")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("E_Commerce_Inern_Project.Core.Domain.Entity.Colors", "Color")
                        .WithMany("Products")
                        .HasForeignKey("ColorID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("E_Commerce_Inern_Project.Core.Domain.Entity.Size", "Size")
                        .WithMany("Products")
                        .HasForeignKey("SizeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Color");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.ProductRates", b =>
                {
                    b.HasOne("E_Commerce_Inern_Project.Core.Domain.Entity.Product", "Product")
                        .WithMany("ProductRates")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("E_Commerce_Inern_Project.Core.Identity.ApplicationUser", "User")
                        .WithMany("ProductRates")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.ShippingCosts", b =>
                {
                    b.HasOne("E_Commerce_Inern_Project.Core.Domain.Entity.Area", "Area")
                        .WithOne("ShippingCosts")
                        .HasForeignKey("E_Commerce_Inern_Project.Core.Domain.Entity.ShippingCosts", "AraeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.WishList", b =>
                {
                    b.HasOne("E_Commerce_Inern_Project.Core.Domain.Entity.Product", "Product")
                        .WithMany("WishLists")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("E_Commerce_Inern_Project.Core.Identity.ApplicationUser", "User")
                        .WithMany("WishLists")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("E_Commerce_Inern_Project.Core.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("E_Commerce_Inern_Project.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("E_Commerce_Inern_Project.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("E_Commerce_Inern_Project.Core.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_Inern_Project.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("E_Commerce_Inern_Project.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Address", b =>
                {
                    b.Navigation("orders");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Area", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("ShippingCosts")
                        .IsRequired();
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Category", b =>
                {
                    b.Navigation("Product");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.City", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Areas");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Colors", b =>
                {
                    b.Navigation("BannerSlides");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.OrderCoupons", b =>
                {
                    b.Navigation("orders");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductRates");

                    b.Navigation("WishLists");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.ShippingCosts", b =>
                {
                    b.Navigation("orders");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Domain.Entity.Size", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("E_Commerce_Inern_Project.Core.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Payments");

                    b.Navigation("ProductRates");

                    b.Navigation("WishLists");
                });
#pragma warning restore 612, 618
        }
    }
}
